### ISSUE TITLE
Marker 沒有標記/Marker doesn't tag

### ISSUE THREAD

**Issue by peter279k** [shouko/BeeHive#1]
我嘗試了一下，發現沒有把點標記到地圖上，在console裡有顯示出來，請修正!
I tried this app,but I found that the marker does not tag on the map.Please fix it!

**Comment by shouko** [comment]
噢噢 抱歉之前沒有看到 ><
會出現這樣情況的原因應該是因為讀到的點剛好不在一開始 focus 的地圖範圍當中
目前沒有實作自動 focus
把地圖拉遠應該就可以看到點的位置了
